### ISSUE TITLE
Missing Parent Rule

### ISSUE THREAD

**Issue by P-JAYAPRADHA** [samisevenx00/wazuh-rules#1]
```
<rule` id="106000" level="12">
    <if_sid>100535</if_sid>
    <field name="win.eventdata.scriptBlockText">(?i)(-EncodedCommand|-e[nc])\s+[A-Za-z0-9+/=]{20,}</field>
    <description>Detection of encoded command execution in PowerShell</description>
    <mitre>
        <id>T1027</id>
    </mitre>
</rule>
```

In the above rule that you provide as powershell-extra.xml we can't find parent rule <if_sid>100535</if_sid>.
regards,
jayapradha p

**Comment by samisevenx00** [comment]
Hi dear,

You can find other rules here (include parent 100535) :

https://github.com/socfortress/Wazuh-Rules/blob/main/Windows%20Powershell/100535-win_powershell_rules.xml
